### ISSUE TITLE
Copy updates to Help, About, Copyright

### ISSUE THREAD

**Issue by danrademacher** [GreenInfo-Network/nyc-crash-mapper#107]
## Copyright
![image](https://user-images.githubusercontent.com/1423200/77357542-92993680-6d05-11ea-996a-482eae3bf798.png)

change to 2020. I don't suppose JS can just pop in "current year"?

## Add to bottom of Help

CRASHMAPPER Vehicle Filter:
When selecting a vehicle type, the numbers returned will be those relating to any crash where
the vehicle is _involved_. Please note these technical limitations:
- NYPD officers use free form entries to report the vehicle involved in a crash. CHEKPEDS maps
these entries to eight categories.
- NYPD captures up to five (5) vehicles included in a crash. As long as one of these vehicles
matches the filter selected, the related injuries and fatalities will be counted – even if the
vehicle is potentially not directly responsible for the fatalities/injuries.

Right now, this is the only one without a video. If easy to just run it full width, let's do that. If easier to have a blank left column, do that. I'd like her to make a video for consistency, but she hasn't done so yet (we need to deploy the filter first)

## Update to About

There's a single new paragraph added here un Enhanced Data. I highlighted it here:
https://docs.google.com/document/d/1Xb274S0ud7D0o2XX1n4AlZdXG0_K9O11/edit

**Comment by gregallensworth** [comment]
- [ ] Copyright

- [ ] CRASHMAPPER Vehicle Filter to Help

- [ ] About, Enhanced Data paragraph

**Comment by gregallensworth** [comment]
These changes are in place in the `gda-vehiclefilter` branch.

Perhaps we should keep this issue open even after deployment, for the forthcoming vehicle filter video?

**Comment by danrademacher** [comment]
Drat, I missed two changes in her unmarked up About copy change. Asked for a highlight version after she said we missed some changes:
![image](https://user-images.githubusercontent.com/1423200/77476705-4834ba00-6dd8-11ea-9f4e-053f41e919df.png)

>The [LILY AUCHINCLOSS FOUNDATION](https://lilynyc.org/) generous grant helped to write the vehicular analysis modules. 
and add
>by Chris Henrick

**Comment by gregallensworth** [comment]
Done.
* LILY AUCHINCLOSS FOUNDATION
* Chris Henrick
