### ISSUE TITLE
Download data button no longer works, appears to Vehicle type related

### ISSUE THREAD

**Issue by danrademacher** [GreenInfo-Network/nyc-crash-mapper#109]
User report and confirmed:
![image](https://user-images.githubusercontent.com/1423200/77862563-3e90c500-71d1-11ea-8e9c-f5177d7d8d6a.png)

I can't tel where Download Data is getting its SQL, but I imagine it might be a different place to which we didn't know to add vehicle type queries?

**Comment by gregallensworth** [comment]
Fixed and deployed.
