### ISSUE TITLE
localhost navbar links try to connect to a different port

### ISSUE THREAD

**Issue by tomay** [GreenInfo-Network/nyc-crash-mapper#69]
The readme says to start a local instance of the app with `npm run serve`, which starts the app on `localhost:8080`. But the navbar links (apart from "About"), are all to `localhost:8889`.

**Comment by clhenrick** [comment]
@tomay that's because the those links go to the [nyc-crash-mapper-chart-view](https://github.com/GreenInfo-Network/nyc-crash-mapper-chart-view) app, which during development can be run on a separate local server. I'll update the README in both apps to make note of this.
