### ISSUE TITLE
Make intersection circle legend

### ISSUE THREAD

**Issue by danrademacher** [GreenInfo-Network/nyc-crash-mapper#82]
Client asked to add it to crash types:
>On map in legend can you add the intersection symbol under none 

But I think that would be weird, esp since it only makes sense when intersections are enabled.

How about something next to the button only when active, like this:
![image](https://user-images.githubusercontent.com/1423200/35527618-37a43f02-04e0-11e8-9668-c63c2dd4f140.png)

That's a span like this
```css
    width: 15px;
    height: 15px;
    background-color: #17838f;
    display: inline-block;
    margin-left: 5px;
    margin-right: 5px;
    vertical-align: middle;
    border-radius: 50%;
    border: 1px solid white;
    opacity: 0.7;
```

Main downside here is it will push the intersection name even further over. Hmm.

**Comment by danrademacher** [comment]
I think this idea has legs, though not sure how much impact it will have on the geography name. And whether we should have blue squares next to the other items, to server as legends there as well. 

what do you think?

**Comment by gregallensworth** [comment]
I think that adding a legend item will push the area names over by 2-3 characters, and the space is already barely sufficient for some area names and insufficient for others. "GRAND ST & U..." would become "GRAND ST ..." and "METROPOLITAN" would become "METROPOLIT"

I also don't think it would communicate much.
* Identical blue squares on 5 buttons, and a circle on one and a "blob shape" on the other, would not communicate the same as a legend where many things are visible at once (red trails, blue trails, orange trails).
* If people don't know they can click the blue things, maybe there's another way to communicate that?
  * Right-hand sidebar could have a message while a geotype is picked but not a specific geo: "Click an area on the map to filter crashes within that area", with a special message when Intersection and Custom types are in progress: "Click one of the blue intersections on the map. You may need to zoom in more closely to see some.".

**Comment by danrademacher** [comment]
That is a much better solution.

so this by default:
>Choose a boundary type, then click an area on the map to filter crashes within that area.

![image](https://user-images.githubusercontent.com/1423200/35593820-ee99bba2-05c5-11e8-9423-bdcfb84dae56.png)


and if Intersections is selected, then:
>The 500 most dangerous intersections over last 2 years. Zoom to see 90-foot radius for each.

![image](https://user-images.githubusercontent.com/1423200/35593987-896d61b0-05c6-11e8-8937-01deb27f2dd4.png)

Match text styling to the "Start Year" and "End Year" labels on the filter by date element

**Comment by gregallensworth** [comment]
This is now in place. I also added a custom message for Custom shape, since "click an area on the map" isn't accurate there.

![2018-01-30 17_02_29-start](https://user-images.githubusercontent.com/3117633/35599838-b460963a-05df-11e8-8f92-4d1481c62c5a.png)
![2018-01-30 17_02_40-start](https://user-images.githubusercontent.com/3117633/35599839-b4831ebc-05df-11e8-825f-128b8fb7dfcb.png)
![2018-01-30 17_02_52-start](https://user-images.githubusercontent.com/3117633/35599840-b4a8db70-05df-11e8-87fe-f325ef9252b0.png)
