### ISSUE TITLE
New Help panel

### ISSUE THREAD

**Issue by danrademacher** [GreenInfo-Network/nyc-crash-mapper#90]
Companion to https://github.com/GreenInfo-Network/nyc-crash-mapper-chart-view/issues/89. Reuse About modal container to make room for client-produced how-to videos

## Content

	<iframe src="https://player.vimeo.com/video/254240475" width="640" height="360" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>

Crashmapper Navigation 

Analyze crash data like a pro. With a few clicks, master the information contained in the NYC Open Data Collision dataset, collected by NYPD.  Choose a data view,  filter by dates, geographies and crash type and get maps, charts and information summaries. Share with others.

	<iframe src="https://player.vimeo.com/video/255986407" width="640" height="360" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>

Crashmapper Custom Map 

How is my area of focus (corridor, school zone, business improvement district) fairing in terms of traffic safety? 

	<iframe src="https://player.vimeo.com/video/255986627" width="640" height="360" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>

Crashmapper Trend

How does my neighborhood compares to others and to the borough in terms of traffic safety. 

	<iframe src="https://player.vimeo.com/video/255986283" width="640" height="360" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>

Crashmapper Compare

How has traffic safety changed in my neighborhood since a past period? Are the traffic calming measures working? 

	<iframe src="https://player.vimeo.com/video/255986528" width="640" height="360" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>

Crashmapper Rank

How is this dangerous intersection ranked in the district, borough or city overall ?  Are we concentrating our efforts on the most dangerous intersections?

##  Basic mockup

![image](https://user-images.githubusercontent.com/1423200/36759159-57b0eb2c-1bcb-11e8-83c6-164dfc3d39fe.png)

**Comment by gregallensworth** [comment]
Looking good and coming along well. Actual screenshot:

![image](https://user-images.githubusercontent.com/3117633/36762020-796f610c-1bd6-11e8-92e6-4f366a53f0bf.png)
