### ISSUE TITLE
Some geometries have ID mismatches between Map and Chart app

### ISSUE THREAD

**Issue by danrademacher** [GreenInfo-Network/nyc-crash-mapper#97]
In reviewing #96 I discovered this bug:

It seems like Assembly and Senate URL params aren't carrying over between map and chart. So when I click from Map>Chart, it carries through the Assembly as overall Geo, but doesn't select the specific district I clicked. When I click from Chart to Map, the query doesn't work (just endless spinning wheel) and what I notice on the map is that the name of the selected district in right menu is different whether I click the district on the map or come over from the chart.

I think it has to do with the two apps treating the names differently. 

Here's a selected Assembly on the map:
![image](https://user-images.githubusercontent.com/1423200/48722953-3aff2e00-ebda-11e8-8758-ef22aad50491.png)

the URL for that is http://localhost:8080/#/?cfat=false&cinj=true&endDate=2018-11&geo=assembly&identifier=55&lat=40.66722811557896&lng=-73.91258239746094&lngLats=%255B%255D&mfat=false&minj=true&noInjFat=false&pfat=false&pinj=true&startDate=2017-11&zoom=13

And here's the same on the chart:
![image](https://user-images.githubusercontent.com/1423200/48723038-697d0900-ebda-11e8-9a3a-c61d38c4a8f2.png)

URL there is http://localhost:8889/?cfat=true&cinj=true&geo=assembly&mfat=true&minj=true&p1end=2018-11&p1start=2017-11&p2end=2017-11&p2start=2016-11&pfat=true&pinj=true&primary=Assembly%20District%2055&reference=citywide&trendAggMonths=1&view=trend

And here's the map when I try to navigate back from Trend to Map with an Assembly District selected:
![image](https://user-images.githubusercontent.com/1423200/48723240-edcf8c00-ebda-11e8-8b88-cf9b6b292ed4.png)

So the map says:
`&identifier=55`
and the chart says:
`&primary=Assembly%20District%2055`

Damn, looks like this is a more general problem. Here's City Council:
![image](https://user-images.githubusercontent.com/1423200/48723311-22dbde80-ebdb-11e8-937f-51c6cd2b9ccc.png)

Seems like the Map can accept only integer IDs for these numbered districts, but the chart is passing longer names. Hmm, I wonder how long that's been an issue!

I wonder if the Chart could just filter those strings out of the links to the map? Or maybe there's a better solution here. On the map it is desirable to _display_ only the integer number of the selected district in the right menu, since otherwise they all read as "City Council..."

**Comment by gregallensworth** [comment]
Corroborating Dan's findings earlier:

* When Map links to any of the 3 Chart views, the URL params are `&geo=type_string&identifier=integer`
  * This does select the area type, but not an area as the given `identifier` is not a valid name

* When Chart links to Map, the URL params are `&type_string&identifier=String%20Name%20And%20ID`
  * This does select the area type, the inserts the string area name into the right-hand side bar, but of course does not match any crashes nor an area so there is no zoom and no crashes showing

So yes, two very different concepts of `identifier` which would each need to be rectified in their own way for the two apps. A standardized behavior of using just the `identifier`, instead of a Full Pretty String Name would have been nice here.

**Comment by gregallensworth** [comment]
## Map

As of commit b1c1757 (see the `gda-issue97` branch) the `identifier` URL param is now properly massaged when received from the Chart View.
* The borough is stripped if present (so Neighborhoods work, even those containing spaces etc. in their name).
* If the string ends in a string of digits then these are extracted to form the real `identifier` e.g. `&identifier=Assembly%20District%20111` would become simply `111`
* This looks to act just fine on startup, filtering and zooming the map as one would expect.

**Comment by danrademacher** [comment]
Fixed, tested, deployed
